<#
.SYNOPSIS
  keeptrak-inspect.ps1 — READ-ONLY schema/inventory dump of a KeepTrak (Microsoft Access) database.

.DESCRIPTION
  The plant runs KeepTrak (an Access .mdb/.accdb) for maintenance / PMs. ABIS is replacing it, so the
  first step is to learn the real schema rather than guess at it. This script opens the file READ-ONLY
  through the Microsoft ACE OLEDB provider and reports, for every user table:

      * column list (name, OLEDB type, size, nullability)
      * row count
      * an optional sample of rows, so free-text/lookup columns can be understood

  It NEVER writes to the database. It is also deliberately a PowerShell script rather than a .NET
  project: ACE OLEDB is Windows-only, and adding a Windows-only csproj would break the Linux CI build.

.SAFETY
  * Opens with Mode=Read — no writes, no schema changes.
  * ALWAYS run this against a COPY of the file. Access takes a lock file (.laccdb/.ldb) even for
    readers; pointing it at the live plant database risks locking or corrupting what people are using.
  * Sample output can contain real operational data — mind where you paste the report.

.REQUIREMENTS
  Microsoft ACE OLEDB (12.0 or 16.0). Verify with:
      (New-Object System.Data.OleDb.OleDbEnumerator).GetElements() | Select-Object SOURCES_NAME
  The provider's bitness must match the PowerShell host's (a 32-bit-only ACE needs 32-bit PowerShell).

.EXAMPLE
  ./tools/keeptrak-inspect.ps1 -Path C:\temp\KeepTrak-copy.accdb -OutFile docs/data-model/KEEPTRAK_SCHEMA.md
.EXAMPLE
  ./tools/keeptrak-inspect.ps1 -Path C:\temp\KeepTrak-copy.mdb -SampleRows 5 -Json schema.json
#>
[CmdletBinding()]
param(
    # Path to a COPY of the KeepTrak .mdb/.accdb.
    [Parameter(Mandatory = $true)][string]$Path,
    # Rows to sample per table (0 = none). Samples are truncated per cell to keep the report readable.
    [int]$SampleRows = 3,
    # Write a Markdown report here (otherwise it goes to stdout).
    [string]$OutFile,
    # Also emit the raw schema as JSON (useful for driving the importer's mapping).
    [string]$Json,
    # Database password, if the file is protected.
    [string]$DbPassword,
    # Max characters shown per sampled cell.
    [int]$CellWidth = 40
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Path)) { throw "File not found: $Path" }
$full = (Resolve-Path -LiteralPath $Path).Path

# --- pick a provider -------------------------------------------------------------------------
$available = @()
try {
    $available = (New-Object System.Data.OleDb.OleDbEnumerator).GetElements() |
        Select-Object -ExpandProperty SOURCES_NAME
} catch { }
$provider = $null
foreach ($p in @('Microsoft.ACE.OLEDB.16.0', 'Microsoft.ACE.OLEDB.12.0')) {
    if ($available -contains $p) { $provider = $p; break }
}
if (-not $provider) {
    throw ("No Microsoft ACE OLEDB provider found. Install the Access Database Engine " +
           "redistributable matching this PowerShell's bitness ($([IntPtr]::Size * 8)-bit).")
}

# Mode=Read keeps this a strict reader.
$cs = "Provider=$provider;Data Source=$full;Mode=Read;"
if ($DbPassword) { $cs += "Jet OLEDB:Database Password=$DbPassword;" }

Write-Verbose "Provider: $provider"
$conn = New-Object System.Data.OleDb.OleDbConnection $cs
$conn.Open()

function Get-Scalar([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    try { return $cmd.ExecuteScalar() } finally { $cmd.Dispose() }
}

function Get-Rows([string]$sql) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    $adapter = New-Object System.Data.OleDb.OleDbDataAdapter $cmd
    $dt = New-Object System.Data.DataTable
    # Return the DataTable WRAPPED IN AN ARRAY: PowerShell unrolls a returned DataTable into its
    # DataRows, which would leave the caller with no .Columns to read.
    try { [void]$adapter.Fill($dt); return ,$dt } finally { $adapter.Dispose(); $cmd.Dispose() }
}

try {
    # User tables only — skip Access's own MSys* catalog tables.
    $tablesSchema = $conn.GetSchema('Tables')
    $tables = $tablesSchema |
        Where-Object { $_.TABLE_TYPE -eq 'TABLE' -and $_.TABLE_NAME -notlike 'MSys*' } |
        Select-Object -ExpandProperty TABLE_NAME | Sort-Object

    $columnsSchema = $conn.GetSchema('Columns')

    $report = New-Object System.Collections.Generic.List[string]
    $model  = New-Object System.Collections.Generic.List[object]

    $report.Add("# KeepTrak schema inventory")
    $report.Add("")
    $report.Add("Source file: ``$([System.IO.Path]::GetFileName($full))``")
    $report.Add("")
    $report.Add("Read-only dump via ``$provider``. Generated by ``tools/keeptrak-inspect.ps1``.")
    $report.Add("")
    $report.Add("## Tables ($($tables.Count))")
    $report.Add("")
    $report.Add("| Table | Rows | Columns |")
    $report.Add("| --- | ---: | ---: |")

    $detail = New-Object System.Collections.Generic.List[string]

    foreach ($t in $tables) {
        # Bracket-quote: KeepTrak table names may contain spaces.
        $count = $null
        try { $count = Get-Scalar "SELECT COUNT(*) FROM [$t]" } catch { $count = 'err' }

        $cols = $columnsSchema | Where-Object { $_.TABLE_NAME -eq $t } |
            Sort-Object ORDINAL_POSITION

        $report.Add("| $t | $count | $($cols.Count) |")

        $detail.Add("")
        $detail.Add("### $t  _(rows: $count)_")
        $detail.Add("")
        $detail.Add("| # | Column | Type | Size | Null |")
        $detail.Add("| ---: | --- | --- | ---: | --- |")

        $colModel = New-Object System.Collections.Generic.List[object]
        foreach ($c in $cols) {
            # DATA_TYPE is the numeric OleDbType; map the common ones to readable names.
            $typeName = switch ([int]$c.DATA_TYPE) {
                2   { 'SmallInt' }    3   { 'Integer' }   4  { 'Single' }    5  { 'Double' }
                6   { 'Currency' }    7   { 'Date' }      11 { 'Boolean' }   17 { 'Byte' }
                72  { 'Guid' }        128 { 'Binary' }    130 { 'WChar' }    131 { 'Numeric' }
                133 { 'DBDate' }      135 { 'DBTimeStamp' } 202 { 'VarChar' } 203 { 'LongVarChar' }
                204 { 'VarBinary' }   205 { 'LongVarBinary' }
                default { "type$($c.DATA_TYPE)" }
            }
            $size = $c.CHARACTER_MAXIMUM_LENGTH
            if ([string]::IsNullOrEmpty([string]$size)) { $size = '' }
            $nullable = 'NOT NULL'
            if ($c.IS_NULLABLE -eq $true) { $nullable = 'null' }

            $detail.Add("| $($c.ORDINAL_POSITION) | $($c.COLUMN_NAME) | $typeName | $size | $nullable |")
            $colModel.Add([pscustomobject]@{
                ordinal = [int]$c.ORDINAL_POSITION
                name    = [string]$c.COLUMN_NAME
                type    = $typeName
                size    = "$size"
                nullable = [bool]$c.IS_NULLABLE
            })
        }

        if ($SampleRows -gt 0 -and $count -is [int] -and $count -gt 0) {
            try {
                $sample = Get-Rows "SELECT TOP $SampleRows * FROM [$t]"
                if ($sample.Rows.Count -gt 0) {
                    $detail.Add("")
                    $detail.Add("_Sample ($($sample.Rows.Count) rows):_")
                    $detail.Add("")
                    $names = @($sample.Columns | ForEach-Object { $_.ColumnName })
                    $detail.Add("| " + ($names -join " | ") + " |")
                    $detail.Add("| " + (($names | ForEach-Object { '---' }) -join " | ") + " |")
                    foreach ($row in $sample.Rows) {
                        $cells = @()
                        foreach ($n in $names) {
                            $val = [string]$row[$n]
                            $val = $val -replace "`r`n", ' ' -replace "`n", ' ' -replace '\|', '\|'
                            if ($val.Length -gt $CellWidth) { $val = $val.Substring(0, $CellWidth) + '…' }
                            $cells += $val
                        }
                        $detail.Add("| " + ($cells -join " | ") + " |")
                    }
                }
            } catch {
                $detail.Add("")
                $detail.Add("_Sample unavailable: $($_.Exception.Message)_")
            }
        }

        $model.Add([pscustomobject]@{ table = $t; rows = $count; columns = $colModel })
    }

    $report.Add("")
    $report.Add("## Columns")
    foreach ($line in $detail) { $report.Add($line) }

    $text = ($report -join [Environment]::NewLine)
    if ($OutFile) {
        $dir = Split-Path -Parent $OutFile
        if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
        $text | Out-File -FilePath $OutFile -Encoding utf8
        Write-Host "Wrote $OutFile ($($tables.Count) tables)."
    } else {
        Write-Output $text
    }

    if ($Json) {
        $dir = Split-Path -Parent $Json
        if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
        $model | ConvertTo-Json -Depth 6 | Out-File -FilePath $Json -Encoding utf8
        Write-Host "Wrote $Json."
    }
}
finally {
    $conn.Close()
    $conn.Dispose()
}
